### ISSUE TITLE
hypre segfaults when running the exawind-driver sphere test

### ISSUE THREAD

**Issue by jrood-nrel** [Exawind/nalu-wind#1285]
Seems like a Nalu-Wind issue:
```
Routine                        Step       Min       Avg       Max
-----------------------------------------------------------------
[New Thread 0x7fff907b6000 (LWP 1653037)]
[New Thread 0x7fff8ffb5000 (LWP 1653044)]
exawind: memory.c:91: void hypre_CheckMemoryLocation(void*, hypre_MemoryLocation): Assertion `location == location_ptr' failed.

Thread 1 "exawind" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
Downloading source file /usr/src/debug/glibc-2.28-251.el8.2.x86_64/signal/../sysdeps/unix/sysv/linux/raise.c
50        return ret;
(gdb) 
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fffdd27ee65 in __GI_abort () at abort.c:79
#2  0x00007fffdd27ed39 in __assert_fail_base (fmt=0x7fffdd3f79c0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=assertion@entry=0x7fffe1d9a1d4 "location == location_ptr", file=file@entry=0x7fffe1d9a0f4 "memory.c",
    line=line@entry=91, function=function@entry=0x7fffe1d9a198 "void hypre_CheckMemoryLocation(void*, hypre_MemoryLocation)")
    at assert.c:92
#3  0x00007fffdd2a3e86 in __GI___assert_fail (assertion=0x7fffe1d9a1d4 "location == location_ptr",
    file=0x7fffe1d9a0f4 "memory.c", line=91,
    function=0x7fffe1d9a198 "void hypre_CheckMemoryLocation(void*, hypre_MemoryLocation)") at assert.c:101
#4  0x00007fffe1c4387c in hypre_CheckMemoryLocation (ptr=0x35149400, location=hypre_MEMORY_DEVICE) at memory.c:91
#5  0x00007fffe1c440e7 in hypre_Memcpy_core (dst=0x7fff72000000, src=0x35149400, size=3165288, loc_dst=hypre_MEMORY_DEVICE,
    loc_src=hypre_MEMORY_DEVICE) at memory.c:623
#6  0x00007fffe1c447c7 in hypre_Memcpy (dst=0x7fff72000000, src=0x35149400, size=3165288, loc_dst=HYPRE_MEMORY_DEVICE,
    loc_src=HYPRE_MEMORY_DEVICE) at memory.c:969
#7  0x00007fffe13a1362 in hypre_IJMatrixSetAddValuesParCSRDevice (matrix=0xd840d0, nrows=791322, ncols=0x0, rows=0x35149400,
    row_indexes=0x0, cols=0x34b3f980, values=0x34231280, action=0x7fffe1c9509b "set") at IJMatrix_parcsr_device.c:148
#8  0x00007fffe138da89 in HYPRE_IJMatrixSetValues2 (matrix=0xd840d0, nrows=791322, ncols=0x0, rows=0x35149400, row_indexes=0x0,
    cols=0x34b3f980, values=0x34231280) at HYPRE_IJMatrix.c:474
#7  0x00007fffe13a1362 in hypre_IJMatrixSetAddValuesParCSRDevice (matrix=0xd840d0, nrows=791322, ncols=0x0, rows=0x35149400,
    row_indexes=0x0, cols=0x34b3f980, values=0x34231280, action=0x7fffe1c9509b "set") at IJMatrix_parcsr_device.c:148
#8  0x00007fffe138da89 in HYPRE_IJMatrixSetValues2 (matrix=0xd840d0, nrows=791322, ncols=0x0, rows=0x35149400, row_indexes=0x0,
    cols=0x34b3f980, values=0x34231280) at HYPRE_IJMatrix.c:474
#9  0x00007ffff46b1eef in sierra::nalu::HypreLinearSystem::hypreIJMatrixSetAddToValues (this=0xead390)
    at /mnt/vdb/home/jrood/exawind/exawind-manager/environments/exawind/nalu-wind/src/HypreLinearSystem.C:1572
#10 0x00007ffff46b3a79 in sierra::nalu::HypreLinearSystem::loadComplete (this=0xead390)
    at /mnt/vdb/home/jrood/exawind/exawind-manager/environments/exawind/nalu-wind/src/HypreLinearSystem.C:1862
#11 0x00007ffff43de4fd in sierra::nalu::EquationSystem::assemble_and_solve (this=0xeacf00, deltaSolution=0xeb1900)
    at /mnt/vdb/home/jrood/exawind/exawind-manager/environments/exawind/nalu-wind/src/EquationSystem.C:320
#12 0x00007ffff445efdf in sierra::nalu::MomentumEquationSystem::assemble_and_solve (this=0xeacf00, deltaSolution=0xeb1900)
    at /mnt/vdb/home/jrood/exawind/exawind-manager/environments/exawind/nalu-wind/src/LowMachEquationSystem.C:2706
#13 0x00007ffff445294b in sierra::nalu::LowMachEquationSystem::solve_and_update (this=0xeacb90)
    at /mnt/vdb/home/jrood/exawind/exawind-manager/environments/exawind/nalu-wind/src/LowMachEquationSystem.C:768
#14 0x00007ffff43eeea0 in sierra::nalu::EquationSystems::solve_and_update (this=0xb43100)
    at /mnt/vdb/home/jrood/exawind/exawind-manager/environments/exawind/nalu-wind/src/EquationSystems.C:822
#15 0x00007ffff454ef3a in sierra::nalu::Realm::nonlinear_iterations (this=0xb42eb0, numNonLinearIterations=1)
    at /mnt/vdb/home/jrood/exawind/exawind-manager/environments/exawind/nalu-wind/src/Realm.C:1979
#16 0x00007ffff454ee20 in sierra::nalu::Realm::advance_time_step (this=0xb42eb0)
    at /mnt/vdb/home/jrood/exawind/exawind-manager/environments/exawind/nalu-wind/src/Realm.C:1964
#17 0x0000000000454637 in exawind::NaluWind::advance_timestep (this=0xa41d80, inonlin=0)
    at /mnt/vdb/home/jrood/exawind/exawind-manager/environments/exawind/exawind/src/NaluWind.cpp:98
```

**Comment by jrood-nrel** [comment]
Yeah it's a different segfault now.
